# Generated by Django 5.0.1 on 2024-01-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceMissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rocket', models.CharField(max_length=255)),
                ('rocketStatus', models.CharField(choices=[('R', 'Retired'), ('A', 'Active')], max_length=1)),
                ('succes', models.BooleanField()),
            ],
        ),
    ]
