# Generated by Django 5.0.1 on 2024-01-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacemissions',
            old_name='succes',
            new_name='success',
        ),
    ]
