# Generated by Django 5.0.1 on 2024-01-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_succes_spacemissions_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemissions',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
