# Generated by Django 5.0.1 on 2024-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_spacemissions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemissions',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
