# Generated by Django 5.0.1 on 2024-01-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_spacemissions_rocketstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacemissions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='spacemissions',
            name='time',
        ),
        migrations.AddField(
            model_name='spacemissions',
            name='launched',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
