# Generated by Django 5.0.1 on 2024-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_spacemissions_date_remove_spacemissions_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronauts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('mission', models.CharField(max_length=255)),
            ],
        ),
    ]
